export enum Directions {
  RTL = 'rtl',
  LTR = 'ltr',
}

export enum Languages {
  ENGLISH = 'en',
  ARABIC = 'ar',
}

export enum Routes {
  ROOT = '',
  AUTH = 'auth',
  DASHBOARDS = 'dashboards',
  UNAUTHORIZED = 'unauthorized',
  CHOSEROLE = 'chose-role',
  EMAILVERIFICATION = 'email-verification',
  NOTIFICATIONS = 'notifications',
}

export enum Pages {
  USERS = 'users',
  NEW = 'new',
  TESTS = 'tests',
  LOGIN = 'login',
  BENEFICIARYSIGNUP = 'Beneficiarysignup',
  ADMIN = 'admin',
  ORGANIZATION = 'organization',
  EMPLOYEES = 'employees',
  TEACHER = 'teacher',
  CHILDREN = 'children',
  PARENT = 'parent',
  ENRICHER = 'enricher',
  DEALS = 'deals',
  PROPOSALS = 'proposals',
}

export enum AccountType {
  PARENT = 'parent',
  TEACHER = 'teacher',
  ORGANIZATION = 'organization',
  ENRICHER = 'enricher',
}

export enum InputTypes {
  TEXT = 'text',
  EMAIL = 'email',
  PASSWORD = 'password',
  NUMBER = 'number',
  DATE = 'date',
  TIME = 'time',
  DATE_TIME_LOCAL = 'datetime-local',
  CHECKBOX = 'checkbox',
  RADIO = 'radio',
  SELECT = 'select',
  TEXTAREA = 'textarea',
  FILE = 'file',
  IMAGE = 'image',
  COLOR = 'color',
  RANGE = 'range',
  TEL = 'tel',
  URL = 'url',
  SEARCH = 'search',
  MONTH = 'month',
  WEEK = 'week',
  HIDDEN = 'hidden',
  MULTI_SELECT = 'multi select',
  MARKDOWN = 'markdown',
}

export enum StatusCode {
  BADREQUEST = 400,
  UNAUTHORIZED = 401,
  FORBIDDEN = 403,
  NOTFOUND = 404,
  CONFLICT = 409,
  GONE = 410,
  OK = 200,
  CREATED = 201,
  INTERNALSERVERERROR = 500,
}
export enum Navigate {
  NEXT = 'next',
  PREV = 'prev',
}
export enum Responses {
  SUCCESS = 'success',
  ERROR = 'error',
  WARNING = 'warning',
  INFO = 'info',
}

export enum SortOrder {
  ASC = 'asc',
  DESC = 'desc',
}

export enum SortBy {
  CREATED_AT = 'createdAt',
  UPDATED_AT = 'updatedAt',
  NAME = 'name',
  EMAIL = 'email',
  PHONE = 'phone',
  STATUS = 'status',
  START_DATE = 'startDate',
  END_DATE = 'endDate',
}

export enum AuthMessages {
  LOGIN_SUCCESS = 'Login successfully',
  LOGOUT_SUCCESS = 'Logout successfully',
  REGISTER_SUCCESS = 'Register successfully',
  FORGET_PASSWORD_SUCCESS = 'Forget password successfully',
  RESET_PASSWORD_SUCCESS = 'Reset password successfully',
}

export enum Methods {
  GET = 'GET',
  POST = 'POST',
  PUT = 'PUT',
  PATCH = 'PATCH',
  DELETE = 'DELETE',
}

export enum Environments {
  PROD = 'production',
  DEV = 'development',
}
export enum UserRole {
  ADMIN = 'ADMIN',
  ORGANIZATIONOWNER = 'ORGANIZATIONOWNER',
  TEACHER = 'TEACHER',
  PARENT = 'PARENT',
  ENRICHER = 'ENRICHER',
}

export enum FormTypes {
  SIGNIN = 'SIGNIN',
  EMPLOYEE = 'EMPLOYEE',
  EMPLOYEE_UPDATE = 'EMPLOYEE_UPDATE',
  TEACHER = 'teacher',
  TEACHER_UPDATE = 'teacherUpdate',
  GRADE = 'grade',
  GRADE_UPDATE = 'gradeUpdate',
  CLASS = 'class',
  CLASS_UPDATE = 'classUpdate',
  CHILD_ORG = 'childOrg',
  CHILD_UPDATE = 'childUpdate',
  CHILD_PRIVATE = 'childPrivate',
  CHILD_ADMIN = 'childAdmin',
  TEST = 'TESTS',
}

export enum OrganizationType {
  CENTER = 'center',
  NURSERY = 'nursery',
  TRAINING = 'training',
  SCHOOL = 'school',
}
export enum ApprovalStatus {
  PENDING = 'pending',
  APPROVED = 'approved',
  REJECTED = 'rejected',
}

export enum Gender {
  MALE = 'male',
  FEMALE = 'female',
}

export enum Endpoint {
  EVALUATIONS = 'evaluations',
  ATTEMPTS = 'attempts',
  AVAILABLE = 'available',
  DETAILS = 'details',
  FORM = 'form',
  CHILD = 'child',
  APPROVE = 'approve',
  SAVE = 'save',
  SUBMIT = 'submit',
  START = 'start',
  RETAKE = 'retake',
  REQUEST_EXTRA = 'request-extra',
  TRANSFERS = 'child-transfers',
  PAYMENTS = 'payments',
  INITIATE = 'initiate',
  RETRY = 'retry',
  CHECKOUT = 'checkout',
  TEACHERS = 'teachers',
  MAILER = 'mailer',
  VERIFYEMAIL = 'verify-email',
  ROLES = 'roles',
  ORGANIZATIONOWNER = 'organization-owner',
  TESTS = 'tests',
  ALL = 'all',
  AUTH = 'auth',
  BENEFICIARIESSIGNUP = 'beneficiaries-signup',
  ENRICHERS_SIGNUP = 'enrichers-signup',
  PARENT_SIGNUP = 'parent-signup',
  EMPLOYEES = 'employees',
  EMPLOYEESBYORGNIZATION = `${EMPLOYEES}/organization`,
  USERS = 'users',
  ORGANIZATIONS = 'organizations',
  ME = 'me',
  PENDING = 'pending',
  REJECT = 'reject',
  CHILDREN = 'children',
  GRADES = 'grades',
  PARENT = 'parent',
  PARENTS = 'parents',
  OWNER = 'owner',
  REPORTS = 'reports',
  STATUS = 'status',
  SUMMARY = 'summary',
  REMINDER = 'reminder',
  CLASSES = 'classes',
  FILTERS = 'filters',
  NOTIFICATIONS = 'notifications',
  UNREAD_COUNT = 'unread-count',
  READ_ALL = 'read-all',
  READ = 'read',
  DISPATCH = 'dispatch',
  DEALS = 'deals',
  PROPOSALS = 'proposals',
  ACTIVITIES = 'activities',
  ENRICHERS = 'enrichers',
  ORG_CHILDREN = 'org-children',
  SELECT = 'select',
  ASSIGN = 'asign',
  GET_CHILDREN = 'get-children',
  WITH_DEALS = 'with-deals',
  WEBHOOK = 'webhook',
  UPLOADS = 'uploads',
  SEARCH = 'search',
  CAPACITY_REQUESTS = 'capacity-requests',
}

export enum ApiErrorCodes {
  AUTH_UNAUTHORIZED = 'AUTH.UNAUTHORIZED',
  AUTH_INVALID_CREDENTIALS = 'AUTH.INVALID_CREDENTIALS',
  AUTH_FORBIDDEN = 'AUTH.FORBIDDEN',
  AUTH_REFRESH_TOKEN_MISSING = 'AUTH.REFRESH_TOKEN_MISSING',
  AUTH_SESSION_COMPROMISED = 'AUTH.SESSION_COMPROMISED',
  AUTH_TOKEN_INVALID = 'AUTH.TOKEN_INVALID',
  AUTH_TOKEN_EXPIRED = 'AUTH.TOKEN_EXPIRED',
  AUTH_LOGOUT_FAILED = 'AUTH.LOGOUT_FAILED',

  USER_NOT_FOUND = 'USER.NOT_FOUND',
  USER_ALREADY_EXISTS = 'USER.ALREADY_EXISTS',
  USER_EMAIL_IN_USE = 'USER.EMAIL_IN_USE',
  USER_PHONE_IN_USE = 'USER.PHONE_IN_USE',

  ORGANIZATION_NOT_FOUND = 'ORGANIZATION.NOT_FOUND',
  ORGANIZATION_ALREADY_EXISTS = 'ORGANIZATION.ALREADY_EXISTS',
  ORGANIZATION_NOT_APPROVED = 'ORGANIZATION.NOT_APPROVED',
  ORGANIZATION_ALREADY_APPROVED = 'ORGANIZATION.ALREADY_APPROVED',
  ORGANIZATION_ALREADY_REJECTED = 'ORGANIZATION.ALREADY_REJECTED',

  CHILD_NOT_FOUND = 'CHILD.NOT_FOUND',
  CHILD_LIMIT_REACHED = 'CHILD.LIMIT_REACHED',
  CHILD_ACCESS_DENIED = 'CHILD.ACCESS_DENIED',
  CHILD_ALREADY_ASSIGNED = 'CHILD.ALREADY_ASSIGNED',
  CHILD_INVALID_TYPE = 'CHILD.INVALID_TYPE',
  CHILD_DUPLICATE = 'CHILD.DUPLICATE',

  TEACHER_NOT_FOUND = 'TEACHER.NOT_FOUND',
  TEACHER_ALREADY_EXISTS = 'TEACHER.ALREADY_EXISTS',

  GRADE_NOT_FOUND = 'GRADE.NOT_FOUND',
  GRADE_ALREADY_EXISTS = 'GRADE.ALREADY_EXISTS',

  CLASS_NOT_FOUND = 'CLASS.NOT_FOUND',
  CLASS_ALREADY_EXISTS = 'CLASS.ALREADY_EXISTS',
  CLASS_FULL = 'CLASS.FULL',

  EVALUATION_NOT_FOUND = 'EVALUATION.NOT_FOUND',
  EVALUATION_ATTEMPT_NOT_FOUND = 'EVALUATION.ATTEMPT_NOT_FOUND',
  EVALUATION_ATTEMPT_LOCKED = 'EVALUATION.ATTEMPT_LOCKED',
  EVALUATION_MAX_ATTEMPTS_REACHED = 'EVALUATION.MAX_ATTEMPTS_REACHED',
  EVALUATION_DIMENSION_MISSING = 'EVALUATION.DIMENSION_MISSING',
  EVALUATION_DUPLICATE_DIMENSIONS = 'EVALUATION.DUPLICATE_DIMENSIONS',
  EVALUATION_DUPLICATE_ANSWERS = 'EVALUATION.DUPLICATE_ANSWERS',
  EVALUATION_INVALID_TRANSITION = 'EVALUATION.INVALID_TRANSITION',
  EVALUATION_SLOT_NOT_FOUND = 'EVALUATION.SLOT_NOT_FOUND',
  EVALUATION_INVALID_QUESTION = 'EVALUATION.INVALID_QUESTION',
  EVALUATION_INVALID_ANSWER = 'EVALUATION.INVALID_ANSWER',
  EVALUATION_NOT_SUITABLE_AGE = 'EVALUATION.NOT_SUITABLE_AGE',
  EVALUATION_NOT_AVAILABLE = 'EVALUATION.NOT_AVAILABLE',

  PAYMENT_NOT_FOUND = 'PAYMENT.NOT_FOUND',
  PAYMENT_FAILED = 'PAYMENT.FAILED',
  PAYMENT_EXPIRED = 'PAYMENT.EXPIRED',
  PAYMENT_MAX_RETRIES = 'PAYMENT.MAX_RETRIES',
  PAYMENT_INVALID_PROVIDER = 'PAYMENT.INVALID_PROVIDER',
  PAYMENT_CURRENCY_NOT_SUPPORTED = 'PAYMENT.CURRENCY_NOT_SUPPORTED',
  PAYMENT_WEBHOOK_INVALID = 'PAYMENT.WEBHOOK_INVALID',
  PAYMENT_WEBHOOK_MISSING = 'PAYMENT.WEBHOOK_MISSING',
  PAYMENT_PROVIDER_UNAVAILABLE = 'PAYMENT.PROVIDER_UNAVAILABLE',
  PAYMENT_INVALID_JSON = 'PAYMENT.INVALID_JSON',

  DEAL_NOT_FOUND = 'DEAL.NOT_FOUND',
  DEAL_CLOSED = 'DEAL.CLOSED',
  DEAL_DEADLINE_PASSED = 'DEAL.DEADLINE_PASSED',
  DEAL_DUPLICATE_PROPOSAL = 'DEAL.DUPLICATE_PROPOSAL',
  DEAL_CANNOT_CREATE = 'DEAL.CANNOT_CREATE',
  DEAL_PROPOSAL_NOT_FOUND = 'DEAL.PROPOSAL_NOT_FOUND',
  DEAL_PROPOSAL_INVALID_STATE = 'DEAL.PROPOSAL_INVALID_STATE',

  ACTIVITY_NOT_FOUND = 'ACTIVITY.NOT_FOUND',
  ACTIVITY_HAS_DEALS = 'ACTIVITY.HAS_DEALS',

  TRANSFER_NOT_FOUND = 'TRANSFER.NOT_FOUND',
  TRANSFER_ALREADY_RESOLVED = 'TRANSFER.ALREADY_RESOLVED',
  TRANSFER_INVALID_CHILD_TYPE = 'TRANSFER.INVALID_CHILD_TYPE',

  NOTIFICATION_NOT_FOUND = 'NOTIFICATION.NOT_FOUND',
  NOTIFICATION_EMAIL_REQUIRED = 'NOTIFICATION.EMAIL_REQUIRED',

  CAPACITY_NOT_FOUND = 'CAPACITY.NOT_FOUND',
  CAPACITY_ACCESS_DENIED = 'CAPACITY.ACCESS_DENIED',

  DB_UNIQUE_VIOLATION = 'DB.UNIQUE_VIOLATION',
  DB_FOREIGN_KEY_VIOLATION = 'DB.FOREIGN_KEY_VIOLATION',
  DB_NOT_NULL_VIOLATION = 'DB.NOT_NULL_VIOLATION',
  DB_CHECK_VIOLATION = 'DB.CHECK_VIOLATION',
  DB_ERROR = 'DB.ERROR',

  RATE_LIMIT_EXCEEDED = 'RATE_LIMIT.EXCEEDED',
  INTERNAL_UNEXPECTED = 'INTERNAL.UNEXPECTED',
  VALIDATION_FAILED = 'VALIDATION.FAILED',

  VALIDATION_ERROR = 'VALIDATION_ERROR',
  FORBIDDEN = 'AUTH.FORBIDDEN',
  UNAUTHORIZED = 'AUTH.UNAUTHORIZED',
  NOT_FOUND = 'USER.NOT_FOUND',
  CONFLICT = 'DB.UNIQUE_VIOLATION',
  INTERNAL_SERVER_ERROR = 'INTERNAL.UNEXPECTED',
  SESSION_EXPIRED = 'AUTH.TOKEN_EXPIRED',
}
